INSERT INTO effects (id, name, description) VALUES (6, 'Candle', 'Creates a hovering light.');
INSERT INTO effects (id, name, description) VALUES (7, 'Armor Improvement', 'Improves the caster''s armor rating.');
INSERT INTO effects (id, name, description) VALUES (8, 'Convert Health to Magicka', 'Convert health into magicka. Caster can be killed by this effect.');
INSERT INTO effects (id, name, description) VALUES (9, 'Paralyze', 'Targets that fail to resist are paralyzed.');
INSERT INTO effects (id, name, description) VALUES (10, 'Command Daedra', 'Powerful summoned and raised creatures are put under the caster''s control.');
INSERT INTO effects (id, name, description) VALUES (11, 'Conjure Boneman', 'Summons a Boneman Archer from the Soul Cairn wherever the caster is pointing.');
INSERT INTO effects (id, name, description) VALUES (12, 'Conjure Dremora Lord', 'Summons a Dremora Lord.');
INSERT INTO effects (id, name, description) VALUES (13, 'Reanimate People', 'Reanimate a dead body permanently to fight for you. Only works on people.');
INSERT INTO effects (id, name, description) VALUES (14, 'Conjure Familiar', 'Summons a familiar wherever the caster is pointing.');
INSERT INTO effects (id, name, description) VALUES (5, 'Repel Undead', 'All affected undead will flee.');
INSERT INTO effects (id, name, description) VALUES (4, 'Undead Heal', 'Heals the undead target.');
INSERT INTO effects (id, name, description) VALUES (2, 'Boethiah''s Embrace', 'You are able to move more quietly, and opponents that get too close take 5 points poison damage per second.');
INSERT INTO effects (id, name, description) VALUES (1, 'Regenerate Stamina', 'Caster regenerates Stamina faster.');
INSERT INTO effects (id, name, description) VALUES (15, 'Regenerate Magica', 'Caster regenerates Magica faster.');
INSERT INTO effects (id, name, description) VALUES (16, 'Regenerate Health', 'Caster regenerates Health faster.');
INSERT INTO effects (id, name, description) VALUES (3, 'Rstore Health', 'Restores Health to the caster.');
INSERT INTO effects (id, name, description) VALUES (17, 'Fortify Health', 'Increases caster''s Health.');
INSERT INTO effects (id, name, description) VALUES (18, 'Fortify Speech', 'Increases caster''s Speech skill.');
INSERT INTO effects (id, name, description) VALUES (19, 'Fortify Magica', 'Increases caster''s Magica.');
INSERT INTO effects (id, name, description) VALUES (20, 'Fortify Stanima', 'Increases caster''s Stanima');
INSERT INTO effects (id, name, description) VALUES (21, 'Fortify Illusion', 'Decreases caster''s Magica consumption when casting Illusion spells.');
INSERT INTO effects (id, name, description) VALUES (22, 'Fortify Conjuration', 'Decreases caster''s Magica consumption when casting Conjuration spells.');
INSERT INTO effects (id, name, description) VALUES (23, 'Fortify Destruction', 'Decreases caster''s Magica consumption when casting Destruction spells.');
INSERT INTO effects (id, name, description) VALUES (24, 'Fortify Restoration', 'Decreases caster''s Magica consumption when casting Restoration spells.');
INSERT INTO effects (id, name, description) VALUES (25, 'Fortify Alteration', 'Decreases caster''s Magica consumption when casting Alteration spells.');