INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (1, 'Ulfric Stormcloak', 'M', 8, false, true, true, 9);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (2, 'Titus Mede II', 'M', 6, false, true, true, 7);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (3, 'Viarmo', 'M', 1, false, true, true, 1);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (4, 'Delphine', 'F', 4, false, true, true, 2);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (5, 'Savos Aren', 'M', 5, false, true, true, 4);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (6, 'Nocturnal', 'F', null, false, true, true, 8);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (7, 'Kodlak Whitemane', 'M', 8, false, true, true, 5);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (8, 'Paarthurnax', null, null, false, true, true, 3);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (9, 'Astrid', 'F', 8, false, true, true, 6);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (10, 'General Tullius', 'M', 6, false, true, true, 7);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (11, 'Mercer Fray', 'M', 4, false, true, true, 10);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (12, 'Chicken', null, null, false, false, false, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (13, 'Wolf', null, null, true, false, false, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (15, 'Hold Guard', null, null, false, true, false, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (16, 'Blackblood Marauder', 'M', 8, true, false, true, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (17, 'Blackblood Marauder', 'M', 8, true, false, true, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (18, 'Salma', 'F', 10, false, true, true, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (19, 'Ralof', 'M', 8, false, true, true, null);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (20, 'Balgruuf the Greater', 'M', 8, false, true, true, 7);
INSERT INTO s225142.actors (id, name, gender, race, hostility, interactivity, uniqueness, faction) VALUES (14, 'Alduin', null, null, true, false, true, null);